### PR TITLE
Goreleaser Integration

### PR DESCRIPTION
**Pull request by faabiosr**
Integration with Goreleaser to release the app for multiples OS.

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Hey @faabiosr, thanks for the PR!

The tests are failing, probably because we are using `go mod`. Could u take a look?

**Comment by faabiosr** [comment]
OK, I will check!

**Comment by jonatasbaldin** [comment]
Thanks! Just ping me when u do :)

**Comment by jonatasbaldin** [comment]
Fixed the tests. Can you rebase it please?

Also, I think I need to setup API keys for goreleaser/code conv in my CI, right? If so, could u point me on how?

**Comment by faabiosr** [comment]
Rebased!

Well, before merge I recommend you to configure this repository into [codecov.io](https://codecov.io/) to show the code coverage of the project, also add a envvar called `GITHUB_TOKEN` in Travis-CI with a personal token

After the merge, create a `tag` following the semantic versioning (ex: `v0.0.1`) and the goreleaser will build the app saving the result into repository releases page.

**Comment by jonatasbaldin** [comment]
Nice, let's do it!

**Comment by jonatasbaldin** [comment]
(it worked!)

thanks very much ✨

**Pull request merged**
